spring:
  redis:
    jedis:
      pool:
        max-active: 8
        min-idle: 1
        max-wait: -1
    timeout: 10000
    cluster:
      max-redirects: 2
      nodes: 192.168.188.131:7001,192.168.188.131: 7002,192.168.188.131:7003,